version: '3'
services:
  app:
    build:
      context: .
      dockerfile: react.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src  # Adjust the path based on your project structure
