version: "3.7"
services:
    # # Mysql Service
    # mysql:
    #     image: mysql:8.0
    #     container_name: paiement-auto-db
    #     restart: unless-stopped
    #     environment:
    #         MYSQL_DATABASE: receipt_db
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_PASSWORD: root
    #         SERVICE_TAGS: dev
    #         SERVICE_NAME: mysql
    #     volumes:
    #         - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    #     networks:
    #         - cat-website
    mysql:
        container_name: mysql_db
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: receipt_db
        ports:
            - 3306:3306
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - cat-website

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
        - 9001:80
        environment:
        - PMA_ARBITRARY=1
        networks:
            - cat-website

    # Laravel Application Service
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: paiement-auto-laravel
        container_name: paiement-auto-app
        restart: unless-stopped
        # depends_on:
        #     - mysql_db
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - cat-website

    # Nginx Service
    nginx:
        image: nginx:alpine
        container_name: paiement-auto-nginx
        restart: unless-stopped
        depends_on:
            - app
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - cat-website

    # phpMyAdmin Service
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     container_name: paiement-auto-phpmyadmin
    #     restart: always
    #     ports:
    #         - "8181:80"
    #     environment:
    #         - PMA_ARBITRARY=1
    #     depends_on:
    #         - mysql

networks:
    cat-website:
        driver: bridge
