version: '3'

services:

  paiement-auto-app:
    container_name: paiement-auto-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./paiement-auto-app:/var/www/html
    ports:
      - 8000:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: receipt_db
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
