version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Adjusted to map to port 80 in the container
    volumes:
      - ./backend:/var/www/html  # Adjusted to use the 'backend' folder as the volume
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_DATABASE: receipt_db
    ports:
        - "3306:3306"
    volumes:
        - mysql_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"

volumes:
  mysql_data:
